---@type LazySpec
return {
  ---@type LazyPlugin
  -- {
  --   'mikavilpas/yazi.nvim',
  --   dependencies = {
  --     'nvim-lua/plenary.nvim',
  --   },
  --   event = 'VeryLazy',
  --   keys = {
  --     {
  --       '-',
  --       function()
  --         require('yazi').yazi()
  --       end,
  --       desc = 'Open the file manager',
  --     },
  --     {
  --       '<leader>cw',
  --       function()
  --         require('yazi').yazi(nil, vim.fn.getcwd())
  --       end,
  --       desc = 'Open the file manager in the cwd',
  --     },
  --   },
  --   ---@type YaziConfig
  --   opts = {
  --     open_for_directories = true,
  --     -- log_level = vim.log.levels.DEBUG,
  --     -- integrations = {
  --     --   grep_in_directory = function(directory)
  --     --     require("my-telescope-searches").my_live_grep({ cwd = directory })
  --     --   end,
  --     -- },
  --   },
  -- },
  -- {
  --   'Rolv-Apneseth/starship.yazi',
  --   lazy = true,
  --   build = function(plugin)
  --     require('yazi.plugin').build_plugin(plugin)
  --   end,
  -- },
}
